[project]
name = "mhfports"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.15.0",
    "rich>=14.1.0",
    "toml>=0.10.2",
    "typer>=0.16.1",
]
